# This is a basic workflow to help you get started with Actions

name: End2End tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
     branches: [ "develop", "gh-action-e2e"]
  pull_request:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 12

      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable


      # Runs a single command using the runners shell
      - name: End2End_tests
        run: |
          set -e
          cd "$GITHUB_WORKSPACE"
          
          echo "START designer in background using overmind"
          # Start designer in background
          nix-shell --run 'overmind s' &


      - name: Prepare_Playwright
        run: |
          echo "PREPARE PLAYWRIGHT"

          cd "$GITHUB_WORKSPACE/frontend"
          npm install
          npx playwright install
          npx playwright install-deps

      - name: Run_Playwright
        run: |

          cd "$GITHUB_WORKSPACE"
          echo "WAITING FOR DESIGNER"

          sleep 300 #TODO: properly wait for designer to be up and running!

          # nix-shell --run '"$WAITFOR -t 600 http://localhost:8080/api/info'
          # nix-shell --run '"$WAITFOR -t 600 http://localhost:8092/info'
          # nix-shell --run '"$WAITFOR -t 600 http://localhost:4200'

          cd "$GITHUB_WORKSPACE/frontend"
          
          echo "RUN PLAYWRIGHT TESTS"
          PLAYWRIGHT_TARGET_URL="http:/localhost:4200" npm run e2e-all

      - name: Cleanup
        run: |
          cd "$GITHUB_WORKSPACE"
          nix-shell --run 'overmind k'